[package]
name = "csv-ledger"
version = "0.1.0"
edition = "2021"
default-run = "csv-ledger"

[dependencies]
csv = "1.1.6"
progress = "0.2.0"
rand = "0.8.5"
rust_decimal = { version = "1.23.1", features = ["serde-str"] }
serde = { version = "1.0.136", features = ["derive"] }
thiserror = "1.0.30"
